# Generated by Django 3.0 on 2020-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200227_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_owner_condition',
            name='condition',
            field=models.TextField(default='No Conditions', verbose_name='Condition'),
        ),
    ]
