# Generated by Django 3.0 on 2020-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200227_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_owner_condition',
            name='condition',
            field=models.TextField(verbose_name='Condition'),
        ),
    ]
