# Generated by Django 3.0 on 2020-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200227_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='Advance',
            new_name='adv',
        ),
        migrations.AddField(
            model_name='product_details',
            name='condition',
            field=models.TextField(default='hello', verbose_name='Condition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='product_owner_condition',
        ),
    ]
