# Generated by Django 3.0 on 2020-02-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200228_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='adv',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='condition',
            field=models.TextField(verbose_name='Terms and Conditions'),
        ),
    ]
