# Generated by Django 3.0 on 2020-03-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200229_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_profile_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_profile_img', models.ImageField(upload_to='pics/add_product/product_img', verbose_name='Product Profile Image')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product_details')),
            ],
        ),
    ]
