# Generated by Django 3.0 on 2020-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200305_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_with_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedback_without_email',
        ),
        migrations.DeleteModel(
            name='feedback_with_details',
        ),
    ]
